server:
  port: 8085
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: NotificationEvent:com.theater_mgnt.microserivce.event.dto.NotificationEvent,CustomerRegisteredEvent:com.theater_mgnt.microserivce.notification.dto.event.CustomerRegisteredEvent,theater_mgnt.microserivce.identity.dto.event.NotificationEvent:com.theater_mgnt.microserivce.event.dto.NotificationEvent

socketio:
  host: 0.0.0.0
  port: 9093

brevo:
  apiKey: ${BREVO_KEY}
  sender:
    email: theonlytruth25012005@gmail.com
    name: Cifastar