services:
  identity-db:
    image: mysql:8.0
    container_name: identity-db
    restart: always

    environment:
      MYSQL_DATABASE: identity_db
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

    ports:
      - "3306:3306"

    volumes:
      - identity_mysql_data:/var/lib/mysql

    networks:
      - microservices-network

  booking-db:
    image: postgres:16
    container_name: booking-db
    restart: always

    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5433:5432"

    volumes:
      - booking_postgres_data:/var/lib/postgresql/data

    networks:
      - microservices-network

  catalog-db:
    image: postgres:16
    container_name: catalog-db
    restart: always

    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5434:5432"

    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data

    networks:
      - microservices-network

  payment-db:
    image: postgres:16
    container_name: payment-db
    restart: always

    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5435:5432"

    volumes:
      - payment_postgres_data:/var/lib/postgresql/data

    networks:
      - microservices-network

  redis:
    image: redis:7
    container_name: redis
    restart: always

    ports:
      - "6379:6379"

    networks:
      - microservices-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    restart: always

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    ports:
      - "2181:2181"

    networks:
      - microservices-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # PLAINTEXT_HOST dùng cho kết nối từ máy host (localhost:9092)
      # PLAINTEXT dùng cho kết nối nội bộ giữa các container (kafka:29092)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    ports:
      - "9092:9092"

    networks:
      - microservices-network


volumes:
  identity_mysql_data:
  booking_postgres_data:
  catalog_postgres_data:
  payment_postgres_data:


networks:
  microservices-network:
    driver: bridge