server:
  port: 8081
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/identity_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: NotificationEvent:theater_mgnt.microserivce.identity.dto.event.NotificationEvent

    properties:
      hibernate:
        format_sql: true

jwt:
  signerKey: "+PAV/uNVIsN2N1peTkAViUZSSc+t8/wOZQDw8M2+HxBD/2dFy9segSiMPHBr+q97"
  valid-duration: 3600 # in seconds
  refreshable-duration: 36000 # in seconds