server:
  port: 8888

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity_service
              uri: http://${IDENTITY_SERVICE_HOST:localhost}:8081
              predicates:
                - Path=${app.api-prefix}/identity/**
              filters:
                  - StripPrefix=1

            - id: notification_service
              uri: http://${NOTIFICATION_SERVICE_HOST:localhost}:8086
              predicates:
                - Path=${app.api-prefix}/notification/**
              filters:
                  - StripPrefix=1

            - id: catalog_service
              uri: http://${CATALOG_SERVICE_HOST:localhost}:8084
              predicates:
                - Path=${app.api-prefix}/catalog/**
              filters:
                  - StripPrefix=1

            - id: booking_service
              uri: http://${BOOKING_SERVICE_HOST:localhost}:8083
              predicates:
                - Path=${app.api-prefix}/booking/**
              filters:
                  - StripPrefix=1

            - id: payment_service
              uri: http://${PAYMENT_SERVICE_HOST:localhost}:8085
              predicates:
                - Path=${app.api-prefix}/payment/**
              filters:
                  - StripPrefix=1

            - id: socket_io_service
              uri: http://${NOTIFICATION_SERVICE_HOST:localhost}:9093
              predicates:
                - Path=/socket.io/**
