server:
  port: 8083
  servlet:
    context-path: /booking

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://localhost:5433/booking_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: booking-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

services:
  catalog:
    url: http://localhost:8082

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 5000

seat:
  lock:
    ttl-minutes: 10
